<?php

$labels = [];
$labels['replies']  = 'Autoresponder';
$labels['managereplies']  = 'E-Mails automatisch beantworten';
$labels['from']  = 'Von: ';
$labels['until']  = 'Bis: ';
$labels['text']  = 'Text: ';
$labels['datefmt']  = 'JJJJ-MM-TT';
$labels['examplereply']  = 'Ich bin von JJJJ-MM-TT bis JJJJ-MM-TT im Urlaub.';
$labels['responderinformation']  = 'Das Datum muss im folgenden Format eingegeben werden: JJJJ-MM-TT. Alle Felder sind Pflichtfelder.';

$messages = [];
$messages['errnosoaplogon'] = 'Es konnte keine Verbindung zum SOAP-Dienst bei all-inkl.com hergestellt werden.';
$messages['errpreviousinprogress'] = 'Die vorherige Anfrage wird noch bearbeitet, daher konnten keine Änderungen durchgeführt werden. Bitte versuchen Sie es nach kurzer Zeit nochmal.';
$messages['errnothingtodo'] = 'Es gibt keine Änderungen, die gespeichert werden müssen.';
$messages['errsyntaxincorrect'] = 'Es wurde ein Fehler in der Schreibweise der Adressen gefunden.';
$messages['errbadrequest'] = 'Es gab einen Fehler bei der SOAP-Anfrage.';
$messages['successfullysaved'] = 'Die Daten wurden gespeichert.';

?>
