<?php

$labels = [];
$labels['replies']  = 'Autoresponder';
$labels['managereplies']  = 'Automatically answer e-mails';
$labels['from']  = 'From: ';
$labels['until']  = 'Until: ';
$labels['text']  = 'Text: ';
$labels['datefmt']  = 'YYYY-MM-DD';
$labels['examplereply']  = 'I am on vacation from YYYY-MM-DD until YYYY-MM-DD.';
$labels['responderinformation']  = 'Dates must be entered in the following format: YYYY-MM-DD. All fields are mandatory.';

$messages = [];
$messages['errnosoaplogon'] = 'Unable to connect to SOAP server at all-inkl.com.';
$messages['errpreviousinprogress'] = 'The previous request is still in progress, therefore no changes have been made. Please try again in a few moments.';
$messages['errnothingtodo'] = 'There are no changes to save.';
$messages['errsyntaxincorrect'] = 'There was a syntax error in the input.';
$messages['errbadrequest'] = 'There was an error with the SOAP request.';
$messages['successfullysaved'] = 'The data has been saved.';

?>
